// services/frontend/src/components/Picture/PictureGrid.tsx
import { For, type VoidComponent } from "solid-js"
import type { PictureApi } from "api-types"
import { splitInLines } from "../../utils/splitInLines"
import { hstack, vstack } from "../../../styled-system/patterns"
import { Picture } from "./Picture"
import { css } from "../../../styled-system/css"
import { routes } from "../Routes"
import type { SpacingToken } from "../../../styled-system/tokens"

const gap: SpacingToken = "2"

export interface PictureGridProps {
  pictures: readonly PictureApi[]
  sizes?: string
}
export const PictureGrid: VoidComponent<PictureGridProps> = (p) => {
  const lines = () => splitInLines(p.pictures)
  return (
    <div class={vstack({ gap, p: gap, alignItems: "initial" })}>
      <For each={lines()}>
        {(line) => (
          <div
            class={hstack({ gap, alignItems: "initial" })}
            style={{ "aspect-ratio": line.aspectRatio }}
          >
            <For each={line.pictures}>
              {(p) => (
                <a
                  class={css({
                    display: "contents",
                    "& > *": { borderRadius: "md", overflow: "hidden" },
                  })}
                  href={routes.Picture(p.id)}
                >
                  <Picture picture={p} sizes="25vw" />
                </a>
              )}
            </For>
          </div>
        )}
      </For>
    </div>
  )
}

// services/frontend/src/lib/components/PictureGrid.svelte
<script lang="ts">
  import type { PictureApi } from "api-types"
  import Picture from "./Picture.svelte"
  import { makePictureUrl } from "$lib/urls"
  import { splitInLines } from "$lib/splitInLines"

  const { pics }: { pics: PictureApi[] } = $props()
  const lines = $derived(splitInLines(pics))
</script>

<div class="wrapper">
  {#each lines as line}
    <div class="line" style="aspect-ratio: {line.aspectRatio};">
      {#each line.pictures as pic}
        <a class="link" href={makePictureUrl(pic.id)}>
          <Picture {pic} sizes="23vw" />
        </a>
      {/each}
    </div>
  {/each}
</div>

<style>
  .wrapper {
    display: flex;
    flex-direction: column;

    --gap: 8px;
    gap: var(--gap);
  }

  .line {
    display: flex;
    gap: var(--gap);
  }

  .link {
    display: contents;

    :global(> *) {
      border-radius: 6px;
      overflow: hidden;
    }
  }
</style>
